### ISSUE TITLE
How do you insert the pragmas in the code ?

### ISSUE THREAD

**Issue by DonAurelio** [gleisonsdm/DawnCC-Compiler#14]
Hi, I would like to insert pragmas in the c code, Now I'm using Python string format to insert c code in my .cpp file. But I read this project and the paper, so i think there is a more elegant way to insert code in required lines of my .cpp file. Can you give me some advises or options to do that? 

Thanks

**Comment by gleisonsdm** [comment]
Sure! I can try to help you ;)
In truth, we have an annotator that can analyze IR code, generate and annotate C code, 
and insert it in a copy of the original source file. First, are you using LLVM? If yes, you can use our
tool now (I can help you). A second question, please, let me know what are you trying to do, if possible. I need more details to help as you need. 

Regards,

    Gleison

**Comment by DonAurelio** [comment]
Is it possible to communicate by email ? - aurelio.vivas@correounivalle.edu.co

**Comment by gleisonsdm** [comment]
Sure! I sent an email to you.
