### ISSUE TITLE
patch: Prefer print() over dump(), dump() only exists in debug builds.

### ISSUE THREAD

**Issue by dtzWill** [gleisonsdm/DawnCC-Compiler#4]
Proposed patch attached.  `dump()` usually just calls `print()` with a newline anyway, not sure about 3.2's LoopInfo but probably does the same as well.

[print-not-dump.patch.txt](https://github.com/gleisonsdm/DawnCC-Compiler/files/681342/print-not-dump.patch.txt)

**Comment by brenocfg** [comment]
Actually, I'm pretty sure those `dump()`s are only there because @gleisonsdm forgot to remove some of his debugging leftovers before making the initial commit. Requiring a debug build because of this is quite the oversight 😅.

We'll just remove those altogether. Thanks for pointing this out!
