### ISSUE TITLE
Enhancement: Improve presentation on GitHub

### ISSUE THREAD

**Issue by dumblob** [gleisonsdm/DawnCC-Compiler#6]
I'd like to suggest the following.

1. Addition of the link http://cuda.dcc.ufmg.br/dawn/ with one-sentence description to the project description of the GitHub repository/project.
1. Addition of the link http://cuda.dcc.ufmg.br/dawn/ and https://github.com/gleisonsdm/DawnCC-Compiler/ to README.md (so that everybody getting this code from this repository will know where to find additional information).
1. Improvement/rewrite of the current description *a source to source compiler* which doesn't say anything. For newcomers is DawnCC primarily a tool fully automatically (i.e. with no user intervention) and smartly annotating existing C/C++ code with multiprocessing/HPC annotations, thus effectively parallelizing the code (supports both CPUs and GPUs).

**Comment by brenocfg** [comment]
Took a while since apparently contributors don't have permissions to edit the project description, but agreed and done! Thanks for pointing it out.
