### ISSUE TITLE
Enhancement: List supported compilers of the resulting annotated source code

### ISSUE THREAD

**Issue by dumblob** [gleisonsdm/DawnCC-Compiler#7]
Currently external projects find it hard to grasp if they can use DawnCC with their projects, because there is no mention of supported compilers, which are tested or at least expected to work with the generated sources by DawnCC.

Of course there are some pointers like the currently implemented "backends" (OpenMP 4.0 or OpenACC), but that's not enough (it doesn't say anything if it will work or at least had worked once). Currently I guess only newest LLVM and GCC versions are viable.

This information should be present in README.md .

**Comment by brenocfg** [comment]
Good point. Added a bit of information on this (with some caveats) in 12affd1fa4e9edd431aab57af0bc412d03157199.

**Comment by dumblob** [comment]
Great, thanks @brenocfg.
